services:
  postgres:
    image: postgres:16-alpine
    container_name: holy-junk_postgres
    env_file: ".env.db"
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

secrets:
  db_password:
    file: db_pass.secret
  db_root_password:
    file: db_root_pass.secret

volumes:
  pgdata:
